name: Google_Task_Clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  device_preview: ^0.5.5
  localstorage: ^3.0.6+9
  provider: ^4.3.3
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  lint: ^1.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/google_tasks_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 700
