name: google_tasks_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.1
  flutter:
    sdk: flutter
  localstorage: ^4.0.0+1
  provider: ^5.0.0
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/google_tasks_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 700
